### ISSUE TITLE
Integrating Observable Inputs

### ISSUE THREAD

**Issue by harrylojames** [juba/pyobsplot#14]
Hi, 

Really excited to see progress being made on making observable plot available in python!

What is the feasibility of integrating Observable Inputs with this to make the following example possible?

https://observablehq.com/@observablehq/plot-density-weighted?intent=fork

Many thanks,

Harry

**Comment by juba** [comment]
Hi,

In fact integrating Observable Inputs would mean integrating the Observable runtime and stdlib, which is not the scope of `pyobsplot` (I understand that the name *Observable Plot* can make the distinction a bit confusing). 

`pyobsplot` only allows to use Plot in notebooks, not the entire Observable ecosystem. For your information I co-developed [an R package](https://github.com/juba/robservable) that does the latter, but I don't know if there is an equivalent for Python.

**Comment by harrylojames** [comment]
Hi Julien, 

Thank you for the information - not to worry!
