### ISSUE TITLE
question about ObservableHQ 

### ISSUE THREAD

**Issue by cornhundred** [juba/pyobsplot#20]
Hi, I have a few questions related to ObservableHQ and how you've built pyobsplot: 
* Is it possible to import an ObservableHQ notebook into anywidget?
* Are you importing the observable runtime in your anywidget front-end code?

I'm curious if I could reproduce something similar to this widget using notebooks I've made on ObservableHQ.

**Comment by juba** [comment]
Hi, this widget only allows to produce charts with Observable Plot, it has nothing to do with Observable notebooks (except that Plot is developed by Observable). So pyobsplot won't allow you to import notebook cells. And we don't use the observable runtime either.

I created an [R package](https://github.com/juba/robservable/) to import Observable notebook cells, but it will not solve your problem if you're using Python...

**Comment by cornhundred** [comment]
Thanks for the info! Yes, I've seen this robservable library and used the similar library for embedding ObservableHQ plots Python https://github.com/thomasballinger/observable-jupyter and the widget version https://github.com/thomasballinger/observable-jupyter-widget. I'm wondering if we can do something similar using anywidget. I'll definitely check out this repo too. It looks great :)
