### ISSUE TITLE
Mosaic Jupyter Widget

### ISSUE THREAD

**Issue by harrylojames** [juba/pyobsplot#47]
@juba apologies an issue isn't the right place for this but wasn't sure where would be better. Feel free to close. 

Wanted to flag that Mosaic has a [jupyter widget](https://idl.uw.edu/mosaic/jupyter/) for creating an observable plot. It doesn't have all the same features (i.e. the ability to export pngs or use the short hand syntax) but the implementation might be worth a look in any case if it wasn't already on your radar.

**Comment by juba** [comment]
Thanks for the pointer, I didn't know about this.

The project is a bit different than `pyobsplot`, as they developed their own specification language, but it is interesting to see that they are using Observable Plot under the hood. And it is developed by extremely talented people!
